import type { NextPage } from "next";
import Head from "next/head";
import Imagee from "next/image";
import { useEffect, useState } from "react";
import { api } from "../services/api";
import styles from "../styles/Home.module.css";
import "antd/dist/antd.css";
import {
  Button,
  DatePicker,
  version,
  message,
  Layout,
  Menu,
  Breadcrumb,
  Image,
} from "antd";
import {
  DesktopOutlined,
  PieChartOutlined,
  FileOutlined,
  TeamOutlined,
  UserOutlined,
} from "@ant-design/icons";

const { Header, Content, Footer, Sider } = Layout;
const { SubMenu } = Menu;

const Home: NextPage = () => {
  const [date, setDate] = useState(null);
  const handleChange = (value: any) => {
    message.info(
      `Data selecionada: ${value ? value.format("YYYY-MM-DD") : "None"}`
    );
    setDate(value);
  };

  const [aberto, setAberto] = useState();

  const onCollapse = (collapsed: any) => {
    console.log(collapsed);
    setAberto(collapsed);
  };

  useEffect(() => {
    //chamada pra API
    api.get("/servidores").then((response) => {
      console.log(response.data);
    });
  }, []);

  const collapsed = aberto;

  return (
    <Layout style={{ minHeight: "100vh" }}>
      <Sider collapsible collapsed={collapsed} onCollapse={onCollapse}>
        <div className="logo" />
        <Image
          width={80}
          src="https://d1fdloi71mui9q.cloudfront.net/ZOqMGEtMRlqPNw6i9U1n_I2A5NYcX4ro4lqo1"
        />
        <Menu theme="dark" defaultSelectedKeys={["1"]} mode="inline">
          <Menu.Item key="1" icon={<TeamOutlined />}>
            Listar Servidores
          </Menu.Item>
          <Menu.Item key="2" icon={<UserOutlined />}>
            Cadastrar Servidores
          </Menu.Item>
          <Menu.Item key="3" icon={<PieChartOutlined />}>
            Listar Lotação
          </Menu.Item>
          <Menu.Item key="4" icon={<FileOutlined />}>
            Cadastrar Lotação
          </Menu.Item>
          {/* <SubMenu key="sub1" icon={<DesktopOutlined />} title="User">
            <Menu.Item key="3">Tom</Menu.Item>
          </SubMenu> */}
        </Menu>
      </Sider>
      <Layout className="site-layout">
        <Header className="site-layout-background" style={{ padding: 0 }} />
        <Content style={{ margin: "0 16px" }}>
          <Breadcrumb style={{ margin: "16px 0" }}>
            <Breadcrumb.Item>User</Breadcrumb.Item>
            <Breadcrumb.Item>Bill</Breadcrumb.Item>
          </Breadcrumb>
          <div
            className="site-layout-background"
            style={{ padding: 24, minHeight: 360 }}
          >
            Bill is a cat.
          </div>
        </Content>
        <Footer style={{ textAlign: "center" }}>
          <a
            href="https://www.instagram.com/leocraraujo/"
            target="_blank"
            rel="noopener noreferrer"
          >
            Produzido por {" Léo Araújo"}
          </a>
        </Footer>
      </Layout>
    </Layout>
  );

  // return (
  //   <div className={styles.container}>
  //     <Head>
  //       <title>SEAP</title>
  //       <meta name="description" content="Generated by create next app" />
  //       <link rel="icon" href="/favicon.ico" />
  //     </Head>

  //     <main className={styles.main}>
  //       <h1 className={styles.title}>
  //         Olá <a href="https://nextjs.org">Mundo!</a>
  //       </h1>
  //       <DatePicker onChange={handleChange} />
  //       <div style={{ marginTop: 16 }}>
  //         Selected Date: {date ? date.format("YYYY-MM-DD") : " "}
  //       </div>
  //     </main>

  //     <footer className={styles.footer}>
  //       <a
  //         href="https://www.instagram.com/leocraraujo/"
  //         target="_blank"
  //         rel="noopener noreferrer"
  //       >
  //         Produzido por {" Léo Araújo"}
  //         <span className={styles.logo}>
  //           <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
  //         </span>
  //       </a>
  //     </footer>
  //   </div>
  // );
};

export default Home;
