import type { NextPage } from "next";
import Head from "next/head";
import Imagee from "next/image";
import { useEffect, useState } from "react";
import { api } from "../services/api";
import styles from "../styles/Home.module.css";
import { AddFooter } from "../components/Footer";
import { Nav } from "../components/Nav";
import "antd/dist/antd.css";
import { Layout, Menu } from "antd";

import { ServidorLista } from "../components/Servidor-list";
import { AddSider } from "../components/Sider";

const { Header, Content, Footer, Sider } = Layout;
const { SubMenu } = Menu;

const Home: NextPage = () => {
  const [aberto, setAberto] = useState();

  const onCollapse = (collapsed: any) => {
    console.log(collapsed);
    setAberto(collapsed);
  };

  const collapsed = aberto;

  return (
    <Layout style={{ minHeight: "100vh" }}>
      <Sider collapsible collapsed={collapsed} onCollapse={onCollapse}>
        <AddSider />
      </Sider>
      <Layout className="site-layout">
        <Header className="site-layout-background" style={{ padding: 0 }}>
          <Nav />
        </Header>
        <Content style={{ margin: "0 16px" }}>
          {/* <Breadcrumb style={{ margin: "16px 0" }}>
            <Breadcrumb.Item>User</Breadcrumb.Item>
            <Breadcrumb.Item>Bill</Breadcrumb.Item>
          </Breadcrumb> */}
          <div
            className="site-layout-background"
            style={{ padding: 24, minHeight: 360 }}
          >
            <ServidorLista />
          </div>
        </Content>
        <Footer style={{ textAlign: "center" }}>
          <AddFooter />
        </Footer>
      </Layout>
    </Layout>
  );

  // return (
  //   <div className={styles.container}>
  //     <Head>
  //       <title>SEAP</title>
  //       <meta name="description" content="Generated by create next app" />
  //       <link rel="icon" href="/favicon.ico" />
  //     </Head>

  //     <main className={styles.main}>
  //       <h1 className={styles.title}>
  //         Olá <a href="https://nextjs.org">Mundo!</a>
  //       </h1>
  //       <DatePicker onChange={handleChange} />
  //       <div style={{ marginTop: 16 }}>
  //         Selected Date: {date ? date.format("YYYY-MM-DD") : " "}
  //       </div>
  //     </main>

  //     <footer className={styles.footer}>
  //       <a
  //         href="https://www.instagram.com/leocraraujo/"
  //         target="_blank"
  //         rel="noopener noreferrer"
  //       >
  //         Produzido por {" Léo Araújo"}
  //         <span className={styles.logo}>
  //           <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
  //         </span>
  //       </a>
  //     </footer>
  //   </div>
  // );
};

export default Home;
